import type { NextPage } from 'next'
import Head from 'next/head'
import { signOut } from "firebase/auth"

import { auth } from '../firebase/firebase'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      This is the homepage that doesn't do shit right now
      <button onClick={() => signOut(auth)}>Logout</button>
    </div>
  )
}

export default Home
